<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ImportEmployee.aspx.cs" Inherits="iHRM.WebPC.Cpanel.Import.ImportEmployee" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="/Cpanel/Skins/Style/style.css" rel="stylesheet" />
    <script type="text/javascript" src="/Cpanel/Skins/Js/jquery-1.9.0.js"></script>


    
    <!--Reference the SignalR library. -->
    <script type="text/javascript" src="/Scripts/jquery.signalR-1.1.4.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script type="text/javascript" src="/signalr/hubs"></script>

    <script type="text/javascript">
        var chat = $.connection.importEmployeeHub;
        var pMax = 0;

        $(function () {
            stoLog_Record = Ext.data.Record.create([
                { name: "id", type: "string" },
                { name: "status", type: "string" },
                { name: "time", type: "date" },
                { name: "status_code", type: "string" },
                { name: "message", type: "string" }
            ]);

            // Create a function that the hub can call to broadcast messages.
            chat.client.broadcastMessage = function (code, data1, data2) {
                switch (code) {
                    case "log":
                        var r = JSON.parse(data1);
                        if ((r.status_code == 'info' && chkShowInfo.checked) || (r.status_code == 'success' && chkShowSuccess.checked) || (r.status_code == 'warning' && chkShowWarning.checked) || (r.status_code == 'danger' && chkShowDanger.checked)) {
                            var record = new stoLog_Record({
                                id: r.id,
                                status: r.status,
                                time: r.time,
                                status_code: r.status_code,
                                message: r.message
                            });
                            stoLog.insert(0, record);
                            stoLog.commitChanges();
                        }
                        break;
                    case "exec-client-code-false":
                        Ext.Msg.show({ icon: Ext.MessageBox.ERROR, msg: data2, title: 'EXEC ' + data1, buttons: Ext.Msg.OK });
                        break;
                    case "start-import":
                        pMax = parseInt(data1);
                        prg1.updateText("0/" + pMax);
                        break;
                    case "import-prg":
                        var idx = parseInt(data1);
                        prg1.updateProgress(idx / pMax, idx + "/" + pMax);
                        break;

                }
            };

            // Start the connection.
            $.connection.hub.start().done(function () {

            });
        });

        function btnStart_click() {
            var s = "";
            stoMapping.data.items.forEach(function (r) { if (r.data.c2 != undefined && r.data.c2 != '') { s += r.data.c1 + ':' + r.data.c2 + ','; } });
            if (s == "") {
                Ext.Msg.show({ icon: Ext.MessageBox.WARNING, msg: 'Please choose MAPPING!', buttons: Ext.Msg.OK });
                return;
            }

            chat.server.sendFromClient('START', h_FileAttacked.value + "|" + "" + "|" + s);
            btnPlay.setDisabled(true);
            btnStop.setDisabled(false);
        }
        function btnStop_click() {
            chat.server.sendFromClient('STOP', '');
            btnStop.setDisabled(true);
            btnPlay.setDisabled(false);
        }

        function showWError(a) {
            wMsgError.show();
            txtMsgError.setValue($(a).text());
        }
    </script>

    <style type="text/css">
        .tt_statusCode { height: 12px; margin-top: -4px; }
        .t1 { padding-top:5px; }
        .t1 label { margin-right: 10px; }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <ext:ResourceManager ID="ResourceManager1" runat="server" />

            <ext:Store ID="stoLog" runat="server">
                <Reader>
                    <ext:JsonReader IDProperty="id">
                        <Fields>
                            <ext:RecordField Name="id" />
                            <ext:RecordField Name="status" />
                            <ext:RecordField Name="time" Type="Date" />
                            <ext:RecordField Name="status_code" Type="Int" />
                            <ext:RecordField Name="message" />
                        </Fields>
                    </ext:JsonReader>
                </Reader>
            </ext:Store>

            <ext:Hidden ID="h_FileAttacked" runat="server" />
            <ext:Viewport ID="Viewport1" runat="server" Layout="BorderLayout" HideBorders="true" AutoScroll="true">
                <Items>
                    <ext:Panel runat="server" Region="North" LabelWidth="65" Border="false" Height="65" Layout="FormLayout" Padding="10">
                        <Items>
                            <ext:CompositeField runat="server">
                                <Items>
                                    <ext:FileUploadField ID="txtUpFile" runat="server" FieldLabel="File import" ButtonText="Choose file" Width="220" />
                                    <ext:Button ID="btnSearch" runat="server" Icon="Attach" Text="Attack file" AutoPostBack="true" OnClick="btnAttack_Click" />
                                    <ext:Button ID="btnMapping" runat="server" Icon="Map" Text="Mapping" Hidden="true">
                                        <Listeners>
                                            <Click Handler="#{wMapping}.show()" />
                                        </Listeners>
                                    </ext:Button>
                                </Items>
                            </ext:CompositeField>
                            <ext:CompositeField runat="server" FieldLabel="Progress">
                                <Items>
                                    <ext:ProgressBar ID="prg1" Text="0/0" runat="server" Width="170" Hidden="true" />
                                    <ext:Button ID="btnPlay" runat="server" Icon="PlayBlue" Text="Start" Hidden="true">
                                        <Listeners>
                                            <Click Fn="btnStart_click" />
                                        </Listeners>
                                    </ext:Button>
                                    <ext:Button ID="btnStop" runat="server" Icon="Stop" Text="Stop" Hidden="true" Disabled="true">
                                        <Listeners>
                                            <Click Fn="btnStop_click" />
                                        </Listeners>
                                    </ext:Button>

                                    <ext:Panel ID="pnlChkShow" runat="server" Border="false" Width="300" Hidden="true">
                                        <Content>
                                            <div class="t1">
                                                <label><input type="checkbox" id="chkShowInfo" runat="server" checked="checked" /> Info</label>
                                                <label><input type="checkbox" id="chkShowSuccess" runat="server" checked="checked" /> Success</label>
                                                <label><input type="checkbox" id="chkShowWarning" runat="server" checked="checked" /> Warning</label>
                                                <label><input type="checkbox" id="chkShowDanger" runat="server" checked="checked" /> Danger</label>
                                            </div>
                                        </Content>
                                    </ext:Panel>
                                </Items>
                            </ext:CompositeField>
                        </Items>
                    </ext:Panel>

                    <ext:GridPanel ID="grd" runat="server" StoreID="stoLog" Region="Center" AutoExpandColumn="status">
                        <ColumnModel>
                            <Columns>
                                <ext:RowNumbererColumn Header="#" Width="55" />
                                <ext:DateColumn DataIndex="time" Header="Time" Format="dd/MM/yyyy HH:mm:ss" Width="115" />
                                <ext:Column DataIndex="status" Header="Status" />
                                <ext:TemplateColumn Header="Message">
                                    <Template runat="server">
                                        <Html>
                                            <a href="#" onclick="showWError(this)">{message}</a>
                                        </Html>
                                    </Template>
                                </ext:TemplateColumn>                                
                                <ext:TemplateColumn Header="TT" Width="35">
                                    <Template runat="server">
                                        <Html>
                                            <div class="tt_statusCode">
                                            <img alt="{status_code}" src="/Cpanel/Skins/Style/IMG/TT_{status_code}.png" /></div>
                                        </Html>
                                    </Template>
                                </ext:TemplateColumn>
                            </Columns>
                        </ColumnModel>
                    </ext:GridPanel>
                </Items>
            </ext:Viewport>

            <ext:Window ID="wMsgError" runat="server" Layout="FitLayout" Width="350" Height="170" Hidden="true">
                <Items>
                    <ext:TextArea ID="txtMsgError" runat="server" ReadOnly="true">
                    </ext:TextArea>
                </Items>
            </ext:Window>
                        
            <ext:Window ID="wMapping" runat="server" Layout="FitLayout" Width="450" Height="270" Hidden="true" Title="MAPPING">
                <Items>
                    <ext:GridPanel ID="grdMapping" runat="server" Border="false">
                        <Store>
                            <ext:Store ID="stoMapping" runat="server">
                                <Reader>
                                    <ext:JsonReader IDProperty="c1">
                                        <Fields>
                                            <ext:RecordField Name="c1" />
                                            <ext:RecordField Name="c1Text" />
                                            <ext:RecordField Name="c2" />
                                        </Fields>
                                    </ext:JsonReader>
                                </Reader>
                            </ext:Store>
                        </Store>
                        <ColumnModel>
                            <Columns>
                                <ext:Column Header="Column" DataIndex="c1Text" Width="200" />
                                <ext:Column Header="Mapping" DataIndex="c2" Width="200">
                                    <Editor>
                                        <ext:ComboBox runat="server" DisplayField="c1Text" ValueField="c1">
                                            <Store>
                                                <ext:Store ID="stoColMapping" runat="server">
                                                    <Reader>
                                                        <ext:JsonReader IDProperty="c1">
                                                            <Fields>
                                                                <ext:RecordField Name="c1" />
                                                                <ext:RecordField Name="c1Text" />
                                                            </Fields>
                                                        </ext:JsonReader>
                                                    </Reader>
                                                </ext:Store>
                                            </Store>
                                        </ext:ComboBox>
                                    </Editor>
                                </ext:Column>
                            </Columns>
                        </ColumnModel>
                    </ext:GridPanel>
                </Items>
            </ext:Window>

            
        </div>

    </form>
</body>
</html>
