<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Import.aspx.cs" Inherits="iHRM.WebPC.Cpanel.QuetThe.Import" %>

<%@ Register Src="../UC/ImageUploader.ascx" TagName="ImageUploader" TagPrefix="uc1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="/Cpanel/Skins/Style/style.css" rel="stylesheet" />
    <script type="text/javascript" src="/Cpanel/Skins/Js/jquery-1.9.0.js"></script>


    
    <!--Reference the SignalR library. -->
    <script type="text/javascript" src="/Scripts/jquery.signalR-1.1.4.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script type="text/javascript" src="/signalr/hubs"></script>

    <script type="text/javascript">

        function btnStart_click() {
            var s = "";
            stoMapping.data.items.forEach(function (r) { s += r.data.value + ','; });
            if (s == "") {
                Ext.Msg.show({ icon: Ext.MessageBox.WARNING, msg: '#QuetThe_Import.msg_1', buttons: Ext.Msg.OK });
                return;
            }

            h_mapping.setValue(s);
        }
    </script>

    <style type="text/css">
        .tt_statusCode { height: 12px; margin-top: -4px; }
        .t1 { padding-top:5px; }
        .t1 label { margin-right: 10px; }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <ext:ResourceManager ID="ResourceManager1" runat="server" />

            <ext:Hidden ID="h_mapping" runat="server" />
            <ext:Viewport ID="Viewport1" runat="server" Layout="BorderLayout" HideBorders="true" AutoScroll="true">
                <Items>
                    <ext:Panel runat="server" Region="North" LabelWidth="65" Border="false" Height="60" Layout="FormLayout" Padding="10">
                        <Items>
                            <ext:Label runat="server" Text="#QuetThe_Import.note" HideLabel="true" />
                            <ext:CompositeField runat="server">
                                <Items>
                                    <ext:FileUploadField ID="txtUpFile" runat="server" FieldLabel="File import" ButtonText="Choose" Width="220" />
                                    <ext:Button ID="btnMapping" runat="server" Icon="Table" Text="Mapping">
                                        <Listeners>
                                            <Click Handler="#{wMapping}.show();" />
                                        </Listeners>
                                    </ext:Button>
                                    <ext:Button ID="btnSearch" runat="server" Icon="PlayBlue" Text="Import" AutoPostBack="true" OnClick="btnAttack_Click">
                                        <Listeners>
                                            <Click Fn="btnStart_click" />
                                        </Listeners>
                                    </ext:Button>
                                </Items>
                            </ext:CompositeField>
                        </Items>
                    </ext:Panel>

                    <ext:TextArea ID="txtLog" runat="server" Region="Center" ReadOnly="true">
                    </ext:TextArea>
                </Items>
            </ext:Viewport>

            <ext:Window ID="wMapping" runat="server" Title="Mapping" Width="370" Height="220" Hidden="true" Layout="FitLayout">
                <TopBar>
                    <ext:Toolbar runat="server" LabelAlign="Right" LabelWidth="35">
                        <Items>
                            <ext:Label runat="server" Text="#QuetThe_Import.kytu" HideLabel="true" />
                            <ext:Radio ID="ktTab" runat="server" Name="g1" Checked="true" FieldLabel="Tab" />
                            <ext:Radio ID="ktPhay" runat="server" Name="g1" FieldLabel="Dot" />
                        </Items>
                    </ext:Toolbar>
                </TopBar>
                <Items>
                    <ext:GridPanel ID="grdMapping" runat="server" Border="false">
                        <Store>
                            <ext:Store ID="stoMapping" runat="server">
                                <Reader>
                                    <ext:ArrayReader>
                                        <Fields>
                                            <ext:RecordField Name="ten" />
                                            <ext:RecordField Name="value" />
                                        </Fields>
                                    </ext:ArrayReader>
                                </Reader>
                            </ext:Store>
                        </Store>
                        <ColumnModel>
                            <Columns>
                                <ext:Column Header="Column" DataIndex="ten" />
                                <ext:NumberColumn Header="Index" DataIndex="value" Format="0">
                                    <Editor>
                                        <ext:NumberField runat="server" />
                                    </Editor>
                                </ext:NumberColumn>
                            </Columns>
                        </ColumnModel>
                    </ext:GridPanel>
                </Items>
            </ext:Window>

        </div>

    </form>
</body>
</html>
