//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iHRM.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iHRM.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;func&gt;
        ///  &lt;item Name=&quot;thang&quot; Description=&quot;Tháng đang tính lương&quot; Usage=&quot;&quot; /&gt;
        ///  &lt;item Name=&quot;empoyeeID&quot; Description=&quot;Empoyee ID&quot; Usage=&quot;&quot; /&gt;
        ///  &lt;item Name=&quot;luongCB&quot; Description=&quot;Lương cơ bản&quot; Usage=&quot;&quot; /&gt;
        ///  &lt;item Name=&quot;luongPC&quot; Description=&quot;Lương phụ cấp&quot; Usage=&quot;&quot; /&gt;
        ///  &lt;item Name=&quot;luongCB_cu&quot; Description=&quot;Lương cơ bản cũ&quot; Usage=&quot;&quot; /&gt;
        ///  &lt;item Name=&quot;luongPC_cu&quot; Description=&quot;Lương phụ cấp cũ&quot; Usage=&quot;&quot; /&gt;
        ///
        ///  &lt;item Name=&quot;PC1&quot; Description=&quot;Tiền phụ cấp 1&quot; Usage=&quot;&quot; /&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Luong_Parameter {
            get {
                return ResourceManager.GetString("Luong_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;func&gt;
        ///  &lt;item Name=&quot;Abs&quot; Description=&quot;Returns the absolute value of a specified number.&quot; Usage=&quot;Abs(-1)&quot; /&gt;
        ///  &lt;item Name=&quot;Acos&quot; Description=&quot;Returns the angle whose cosine is the specified number.&quot; Usage=&quot;Acos(1)&quot; /&gt;
        ///  &lt;item Name=&quot;Asin&quot; Description=&quot;Returns the angle whose sine is the specified number.&quot; Usage=&quot;Asin(0)&quot; /&gt;
        ///  &lt;item Name=&quot;Atan&quot; Description=&quot;Returns the angle whose tangent is the specified number.&quot; Usage=&quot;Atan(0)&quot; /&gt;
        ///  &lt;item Name=&quot;Ceiling&quot; Descri [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MathEvaluator_lstFunction {
            get {
                return ResourceManager.GetString("MathEvaluator_lstFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;func&gt;
        ///  &lt;item Name=&quot;+&quot; Description=&quot;&quot; Usage=&quot;&quot; /&gt;
        ///  &lt;item Name=&quot;-&quot; Description=&quot;&quot; Usage=&quot;&quot; /&gt;
        ///  &lt;item Name=&quot;*&quot; Description=&quot;&quot; Usage=&quot;&quot; /&gt;
        ///  &lt;item Name=&quot;/&quot; Description=&quot;&quot; Usage=&quot;&quot; /&gt;
        ///  &lt;item Name=&quot;^&quot; Description=&quot;&quot; Usage=&quot;&quot; /&gt;
        ///  &lt;item Name=&quot;||&quot; Description=&quot;or&quot; Usage=&quot;&quot; /&gt;
        ///  &lt;item Name=&quot;&amp;amp;&amp;amp;&quot; Description=&quot;and&quot; Usage=&quot;&quot; /&gt;
        ///  &lt;item Name=&quot;=&quot; Description=&quot;&quot; Usage=&quot;&quot; /&gt;
        ///  &lt;item Name=&quot;==&quot; Description=&quot;&quot; Usage=&quot;&quot; /&gt;
        ///  &lt;item Name=&quot;!=&quot; Description=&quot;&quot; Usage=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MathEvaluator_lstOperator {
            get {
                return ResourceManager.GetString("MathEvaluator_lstOperator", resourceCulture);
            }
        }
    }
}
