//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iHRM.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=117.6.160.172;Initial Catalog=sHRM_DEV;User ID=sHRM")]
        public string sHRM_DEVConnectionString1 {
            get {
                return ((string)(this["sHRM_DEVConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.12.0.3;Initial Catalog=YS2_new_1811;Persist Security Info=True;Use" +
            "r ID=sHRM")]
        public string YS2_new_1811ConnectionString {
            get {
                return ((string)(this["YS2_new_1811ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.12.0.3;Initial Catalog=YS2_new_1811;Persist Security Info=True;Use" +
            "r ID=sHRM;Password=123456a@")]
        public string YS2_new_1811ConnectionString1 {
            get {
                return ((string)(this["YS2_new_1811ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.12.0.3;Initial Catalog=ys2_1512;Persist Security Info=True;User ID" +
            "=sHRM;Password=123456a@")]
        public string ys2_1512ConnectionString {
            get {
                return ((string)(this["ys2_1512ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=117.6.160.172;Initial Catalog=sHRM_DEV;User ID=sHRM")]
        public string sHRM_DEVConnectionString {
            get {
                return ((string)(this["sHRM_DEVConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.12.0.3;Initial Catalog=ys2_1512;Persist Security Info=True;User ID" +
            "=sHRM")]
        public string ys2_1512ConnectionString1 {
            get {
                return ((string)(this["ys2_1512ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=117.6.160.172;Initial Catalog=ys2_1512;Persist Security Info=True;Use" +
            "r ID=sHRM")]
        public string ys2_1512ConnectionString2 {
            get {
                return ((string)(this["ys2_1512ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=117.6.160.172;Initial Catalog=ys2_1512;Persist Security Info=True;Use" +
            "r ID=sHRM;Password=123456a@")]
        public string ys2_1512ConnectionString3 {
            get {
                return ((string)(this["ys2_1512ConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.12.0.3;Initial Catalog=WiseEyeV5.12_New01022016SQL;User ID=sHRM;Pa" +
            "ssword=123456a@")]
        public string WiseEyeV5_12_New01022016SQLConnectionString {
            get {
                return ((string)(this["WiseEyeV5_12_New01022016SQLConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.12.0.3;Initial Catalog=ys2_1512;User ID=sHRM")]
        public string ys2_1512ConnectionString4 {
            get {
                return ((string)(this["ys2_1512ConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.12.0.3;Initial Catalog=ys2_1512;User ID=sHRM;Password=123456a@")]
        public string ys2_1512ConnectionString5 {
            get {
                return ((string)(this["ys2_1512ConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=117.6.163.199;Initial Catalog=ys2_1512;User ID=sHRM;Password=123456a@" +
            "")]
        public string ys2_1512ConnectionString6 {
            get {
                return ((string)(this["ys2_1512ConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=117.6.163.199;Initial Catalog=ys2_1512;User ID=sHRM")]
        public string ys2_1512ConnectionString7 {
            get {
                return ((string)(this["ys2_1512ConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LONG-PC;Initial Catalog=YSA_sHRM;Persist Security Info=True;User ID=s" +
            "a")]
        public string YSA_sHRMConnectionString {
            get {
                return ((string)(this["YSA_sHRMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.12.0.3;Initial Catalog=YS2_sHRM;Persist Security Info=True;User ID" +
            "=sHRM")]
        public string YS2_sHRMConnectionString {
            get {
                return ((string)(this["YS2_sHRMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.12.0.3;Initial Catalog=YS2_sHRM;Persist Security Info=True;User ID" +
            "=sHRM;Password=123456a@")]
        public string YS2_sHRMConnectionString1 {
            get {
                return ((string)(this["YS2_sHRMConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.12.0.3;Initial Catalog=SSBM_sHRM;Persist Security Info=True;User I" +
            "D=sa;Password=123456a@")]
        public string SSBM_sHRMConnectionString {
            get {
                return ((string)(this["SSBM_sHRMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.12.0.3;Initial Catalog=DataQuetThe_SSBM_LonG;Persist Security Info" +
            "=True;User ID=sa;Password=123456a@")]
        public string DataQuetThe_SSBM_LonGConnectionString {
            get {
                return ((string)(this["DataQuetThe_SSBM_LonGConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LONG-PC;Initial Catalog=DataQuetThe_SSBM;Persist Security Info=True;U" +
            "ser ID=sa")]
        public string DataQuetThe_SSBMConnectionString {
            get {
                return ((string)(this["DataQuetThe_SSBMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LONG-PC;Initial Catalog=SSBM_sHRM;Integrated Security=True")]
        public string SSBM_sHRMConnectionString1 {
            get {
                return ((string)(this["SSBM_sHRMConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.12.0.3;Initial Catalog=SSBM_sHRM;Persist Security Info=True;User I" +
            "D=sa")]
        public string SSBM_sHRMConnectionString2 {
            get {
                return ((string)(this["SSBM_sHRMConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.0.3;Initial Catalog=SSVN_HR;Persist Security Info=True;User ID=s" +
            "a")]
        public string SSVN_HRConnectionString {
            get {
                return ((string)(this["SSVN_HRConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.0.3;Initial Catalog=SSVN_HR;User ID=sa")]
        public string SSVN_HRConnectionString1 {
            get {
                return ((string)(this["SSVN_HRConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=125.212.134.81;Initial Catalog=SSVN_HR;User ID=sa")]
        public string SSVN_HRConnectionString2 {
            get {
                return ((string)(this["SSVN_HRConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.12.0.3;Initial Catalog=SSBM_sHRM;User ID=sa")]
        public string SSBM_sHRMConnectionString3 {
            get {
                return ((string)(this["SSBM_sHRMConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.12.0.3;Initial Catalog=SSBM_sHRM;User ID=sa;Password=123456a@")]
        public string SSBM_sHRMConnectionString4 {
            get {
                return ((string)(this["SSBM_sHRMConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=125.212.130.240;Initial Catalog=SSBM_sHRM;Persist Security Info=True;" +
            "User ID=sa")]
        public string SSBM_sHRMConnectionString5 {
            get {
                return ((string)(this["SSBM_sHRMConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.5.2;Initial Catalog=DataQuetThe_SSYT;User ID=sa")]
        public string DataQuetThe_SSYTConnectionString {
            get {
                return ((string)(this["DataQuetThe_SSYTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.2.5.2;Initial Catalog=DataQuetThe_SSYT;User ID=sa;Password=123456a" +
            "@")]
        public string DataQuetThe_SSYTConnectionString1 {
            get {
                return ((string)(this["DataQuetThe_SSYTConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=DataQuetThe_SSYT;User ID=sa;Password=123456a@")]
        public string DataQuetThe_SSYTConnectionString2 {
            get {
                return ((string)(this["DataQuetThe_SSYTConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SSYT_sHRM;User ID=sa;Password=123456a@")]
        public string SSYT_sHRMConnectionString {
            get {
                return ((string)(this["SSYT_sHRMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=125.212.134.81;Initial Catalog=sHRM;Persist Security Info=True;User I" +
            "D=sHRM")]
        public string sHRMConnectionString {
            get {
                return ((string)(this["sHRMConnectionString"]));
            }
        }
    }
}
